# Generated by Django 4.2.30 on 2026-08-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={
                "ordering": ["title"],
                "verbose_name": "newspaper",
                "verbose_name_plural": "newspapers",
            },
        ),
    ]
