# Generated by Django 4.2.30 on 2026-08-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_alter_newspaper_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
